name: Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  security-events: write
  contents: read

jobs:
  security-scan:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
